### ISSUE TITLE
Not really an issue.

### ISSUE THREAD

**Issue by J16N** [onemanbuilds/NordVPNChecker#1]
This will probably going to save me. I had been scratching my head from the past few days to get the authentication endpoint but did not succeed. Just out of curiosity, how did you find it out? :D

**Comment by onemanbuilds** [comment]
Hi this is a really old endpoint i thought it won't work but it is. I'm bad at request debugging, but if you don't find api endpoints on your pc, you should try to find it on a phone with ssl pinning if needed. Most of the time i can't find them too and i don't know how people find them that's why i usually use selenium.
